
The following have been reloaded with a version change:
  1) nvhpc/21.9 => nvhpc/23.1


Lmod is automatically replacing "nvhpc/23.1" with "gcc/11.2.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.16

python: no process found
mpiexec: no process found
python: no process found
mpiexec: no process found
python: no process found
mpiexec: no process found
python: no process found
mpiexec: no process found
python: no process found
mpiexec: no process found
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yuke/lyd/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yuke/lyd/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yuke/lyd/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module scaled_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yuke/lyd/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module fused_mix_prec_layer_norm_cuda...
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/home/yuke/lyd/Megatron-LM/pretrain_gpt.py", line 124, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 154, in pretrain
    iteration = train(forward_step_func,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 741, in train
    train_step(forward_step_func,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 417, in train_step
    losses_reduced = forward_backward_func(
  File "/home/yuke/lyd/Megatron-LM/megatron/schedules.py", line 660, in forward_backward_pipelining_without_interleaving
    send_forward(output_tensor, send_tensor_shapes, timers=timers)
  File "/home/yuke/lyd/Megatron-LM/megatron/schedules.py", line 571, in send_forward
    p2p_communication.send_forward(output_tensor, tensor_shape, timers=timers)
  File "/home/yuke/lyd/Megatron-LM/megatron/p2p_communication.py", line 206, in send_forward
    _communicate(
  File "/home/yuke/lyd/Megatron-LM/megatron/p2p_communication.py", line 139, in _communicate
    torch.cuda.synchronize()
  File "/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/cuda/__init__.py", line 688, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[W CUDAGuardImpl.h:124] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14e40faac349 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x14e40fa759d6 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x14e40fb331f2 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x10c97 (0x14e40fb03c97 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x225b3 (0x14e40fb155b3 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x42ef66 (0x14e422507f66 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x14e40fa8acf9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x6b6c58 (0x14e42278fc58 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #8: THPVariable_subclass_dealloc(_object*) + 0x2b6 (0x14e42278ff86 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x12a080 (0x55d45d3fa080 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #10: <unknown function> + 0x12a84c (0x55d45d3fa84c in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #11: <unknown function> + 0x141f87 (0x55d45d411f87 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #12: <unknown function> + 0x141ee9 (0x55d45d411ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #13: <unknown function> + 0x141ee9 (0x55d45d411ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #14: <unknown function> + 0x141ee9 (0x55d45d411ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #15: <unknown function> + 0x141ee9 (0x55d45d411ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #16: <unknown function> + 0x176978 (0x55d45d446978 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #17: PyDict_SetItemString + 0x64 (0x55d45d446cb4 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #18: <unknown function> + 0x2743bd (0x55d45d5443bd in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #19: Py_FinalizeEx + 0x191 (0x55d45d544991 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #20: Py_RunMain + 0x1d5 (0x55d45d549c55 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #21: Py_BytesMain + 0x39 (0x55d45d549ff9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #22: __libc_start_main + 0xef (0x14e472f7224d in /lib64/libc.so.6)
frame #23: <unknown function> + 0x2016a0 (0x55d45d4d16a0 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)

Traceback (most recent call last):
  File "/home/yuke/lyd/Megatron-LM/pretrain_gpt.py", line 124, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 154, in pretrain
    iteration = train(forward_step_func,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 741, in train
    train_step(forward_step_func,
  File "/home/yuke/lyd/Megatron-LM/megatron/training.py", line 417, in train_step
    losses_reduced = forward_backward_func(
  File "/home/yuke/lyd/Megatron-LM/megatron/schedules.py", line 660, in forward_backward_pipelining_without_interleaving
    send_forward(output_tensor, send_tensor_shapes, timers=timers)
  File "/home/yuke/lyd/Megatron-LM/megatron/schedules.py", line 571, in send_forward
    p2p_communication.send_forward(output_tensor, tensor_shape, timers=timers)
  File "/home/yuke/lyd/Megatron-LM/megatron/p2p_communication.py", line 206, in send_forward
    _communicate(
  File "/home/yuke/lyd/Megatron-LM/megatron/p2p_communication.py", line 139, in _communicate
    torch.cuda.synchronize()
  File "/home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/cuda/__init__.py", line 688, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[W CUDAGuardImpl.h:124] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x150e87434349 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x150e873fd9d6 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x150e874bb1f2 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x10c97 (0x150e8748bc97 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x225b3 (0x150e8749d5b3 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x42ef66 (0x150e99e8ff66 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x150e87412cf9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x6b6c58 (0x150e9a117c58 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #8: THPVariable_subclass_dealloc(_object*) + 0x2b6 (0x150e9a117f86 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x12a080 (0x555cdfdfc080 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #10: <unknown function> + 0x12a84c (0x555cdfdfc84c in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #11: <unknown function> + 0x141f87 (0x555cdfe13f87 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #12: <unknown function> + 0x141ee9 (0x555cdfe13ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #13: <unknown function> + 0x141ee9 (0x555cdfe13ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #14: <unknown function> + 0x141ee9 (0x555cdfe13ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #15: <unknown function> + 0x141ee9 (0x555cdfe13ee9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #16: <unknown function> + 0x176978 (0x555cdfe48978 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #17: PyDict_SetItemString + 0x64 (0x555cdfe48cb4 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #18: <unknown function> + 0x2743bd (0x555cdff463bd in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #19: Py_FinalizeEx + 0x191 (0x555cdff46991 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #20: Py_RunMain + 0x1d5 (0x555cdff4bc55 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #21: Py_BytesMain + 0x39 (0x555cdff4bff9 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)
frame #22: __libc_start_main + 0xef (0x150eea8fa24d in /lib64/libc.so.6)
frame #23: <unknown function> + 0x2016a0 (0x555cdfed36a0 in /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python)

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 725 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 727 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 716) of binary: /home/yuke/lyd/conda3/envs/pytorchNCCL-hao/bin/python
x3006c0s37b1n0.hsn.cm.polaris.alcf.anl.gov: rank 2 died from signal 15
